### ISSUE TITLE
Error in installation of Burp-Suite Pro

### ISSUE THREAD

**Issue by INVIZIBLE84** [SNGWN/Burp-Suite-Pro#1]
I'm having a problem while installing professional version of burp-suite.

**Error: Unable to access jarfile burpsuite_pro.jar**

Having this error while installing burp-suite pro
I am trying to installing it on WSL 
Any solution on this ??

**Comment by SNGWN** [comment]
Bro WSL only support CLI, well error is not related to that, but even if you resolve the error and install it, it may not work. 
Its better to directly install it on Windows.

**Comment by INVIZIBLE84** [comment]
I've installed it on my previous WSL machine but for some reasons I have
reseted my PC. So i have to reinstall it. It does work on WSL
